using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;

public class Characterstatus : MonoBehaviour
{
    //상태 설정 값 
    public int hp = 10;                         //플레이어 생명 
    public bool invincible = false;             //무적 상태 
    public bool canMove = true;                 //이동 가능 상태 
    public bool isDashing = false;              //대시 상태 
    public bool canDash = true;                 //대시 가능 여부 상태 
    public float mDashForce = 25f;              //대시 힘의 량 

    //타이머 설정 값 
    public Timer stunTimer = new Timer(0.25f);          //스턴 타이머 0.25초 
    public Timer invincibilityTimer = new Timer(1f);    //무적 타이머 1초 
    public Timer moveTimer = new Timer(0f);
    public Timer checkTimer = new Timer(0f);
    public Timer endSlidingTimer = new Timer(0f);
    public Timer deadTimer = new Timer(1.5f);
    public Timer dashCooldownTimer = new Timer(0.6f);

    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {
        //타이머 업데이트 
        float deltaTime = Time.deltaTime;
        stunTimer.Update(deltaTime);
        invincibilityTimer.Update(deltaTime);
        moveTimer.Update(deltaTime);
        endSlidingTimer.Update(deltaTime);
        deadTimer.Update(deltaTime);
        dashCooldownTimer.Update(deltaTime);

        //타이머 상태 체크 

        if (!stunTimer.IsRunning())              //스턴 타이머 동작 체크
        {
            canMove = true;
        }

        if (!invincibilityTimer.IsRunning())                //무적 타이머 동작 체크
        {
            invincible = false;
        }

        if (!moveTimer.IsRunning())                        //이동 타이머 동작 체크
        {
            canMove = true;
        }

        if (isDashing && !dashCooldownTimer.IsRunning())    //대쉬 타이머 동작 체크
        {
            isDashing = false;
            canMove = true;
            canDash = true;
        }

        if (deadTimer.GetRemainingTime() <= 0)              //죽음 이후 처리
        {
            //씬 처리 등등 해준다.
        }
    }

    public void StartDash(float dashDuration)
    {
        //animator.SetBool("IsDaghing", true)
        isDashing = true;
        canDash = false;
        canMove = false;
        dashCooldownTimer = new Timer(dashDuration);
        dashCooldownTimer.Start();
    }
    public void ApplyDamage(int damage, Vector3 position)
    {
        if(!invincible)
        {
            //animatior.SetBoo("Hit", true)
            hp -= damage;

            if(hp <= 0)
            {
                deadTimer.Start();
            }
            else
            {
                stunTimer.Start();
                invincibilityTimer.Start();
            }
        } 
    }
}
